defaults: &defaults
  app_id: "28062"
  key: "8c3c4693e6fabd4c1120"
  secret: "dc55c4c64b7f4176222c"
development:
  <<: *defaults
test:
  <<: *defaults
production:
  <<: *defaults
  app_id: "28063"
  key: "0adb5e7803810c10b73e"
  secret: "eed63fc63ebb49355111"
